### ISSUE TITLE
Keyboard override (shortcut)

### ISSUE THREAD

**Issue by ghost** [lynk/webext-tabfreezer#1]
Thanks a lot for this useful extension!

One note about keyboard override:
In Firefox for Linux _Alt+[1...8]_ are the unchangeable key bindings for _Select Tab_.
_Alt+1_ is also processed by Tab Freezer in Linux, but concurrently Firefox selects the first tab.

**Comment by lynk** [comment]
Hi WernerFP,
thank you for the feedback and your rating!

I will look into the keyboard shortcut for linux and implement a better solution in the next update.

**Comment by lynk** [comment]
Hi @WernerFP ,

I am concidering "Ctrl+1" as a keyboard shortcut for linux. On Ubuntu they are not used by Firefox, can you confirm this?

thank you

**Comment by ghost** [comment]
Yes, *Ctrl+1* is not used by Firefox for Linux. [[1]](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#firefox:linux:fx62)

In Chrome-based browsers the relevant shortcuts for Windows and Linux are identical (*Ctrl+[1...8 ]* → *Jump to a specific tab*).
